import type { Metadata } from "next";
import "./globals.css";
import "react-country-state-city/dist/react-country-state-city.css";
import "./custom.css";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import ClientLayout from "./ClientLayout";
import { getServerUser } from "./helper/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getServerUser();
  return (
    <html lang="en">
      <body>
        <ClientLayout user={user}>
          <TooltipProvider>
            {children}
          </TooltipProvider>
          <Toaster position="top-right" richColors />
        </ClientLayout>
      </body>
    </html>
  );
}
